# Generated by Django 4.1.2 on 2022-10-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
