# Generated by Django 4.1.2 on 2022-10-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_comments_creator_remove_news_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
