# Generated by Django 4.1.2 on 2022-10-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publication',
            field=models.BooleanField(default=False),
        ),
    ]
