# Generated by Django 4.1.2 on 2022-10-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_news_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='caption',
            field=models.TextField(max_length=3500),
        ),
    ]
