# Generated by Django 4.1.2 on 2022-10-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_news_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='html',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
