# Generated by Django 4.1.2 on 2022-10-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_news_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
